name: '[STAGING] Deploy api'

on:
  push:
    paths:
      - apps/api/**
    branches:
      - next

jobs:
  forge-deploy:
    name: 'Deploy api [laravel forge]'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: jbrooksuk/laravel-forge-action@v1.0.2
        with:
          trigger_url: ${{ secrets.API_STAGING_TRIGGER_URL }}