name: 'Deploy api'

on:
  push:
    paths:
      - apps/api/**
    branches:
      - master

jobs:
  forge-deploy:
    name: 'Deploy api [laravel forge]'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: jbrooksuk/laravel-forge-action@v1.0.2
        with:
          trigger_url: ${{ secrets.API_TRIGGER_URL }}